Typescript support
kuzzleio/kuzzle-vuejs-coreui-boilerplate pull request #10
Opened 2020-11-23 14:34 UTC by jenow

## What does this PR do ?

Add typescript support.

2020-11-23 15:51 UTC, Aschen requested changes

2020-11-23 15:51 UTC, Aschen commented on frontend/package.json
> +    "typescript": "~3.9.3",
You should use TS 4

2020-11-23 16:02 UTC, alexandrebouthinon approved these changes

2020-11-23 16:02 UTC, alexandrebouthinon commented on frontend/.eslintrc.js
> +
Are those blank lines wanted?

2020-11-23 16:07 UTC, jenow commented on frontend/.eslintrc.js
> +
I used vue cli to init typescript and it changed all of this

2020-11-24 15:05 UTC, Aschen approved these changes

2020-11-24 15:05 UTC, merged